-- Run against the selected trananh_billiards database, not the postgres database.
-- Existing tables and records are preserved. This is a baseline, not an upgrade script.
BEGIN;

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL CHECK (btrim(name) <> ''),
    price BIGINT NOT NULL CHECK (price >= 0)
);

COMMIT;
