-- Record the category setup used by Category.java and Product.java.
-- Run after 01-schema.sql in the trananh_billiards database.
BEGIN;

CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL CHECK (btrim(name) <> '')
);

ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS category_id BIGINT
    REFERENCES public.categories(id);

COMMIT;
