spring.application.name=trananh-billiards

spring.datasource.url=jdbc:postgresql://localhost:2706/trananh_billiards
spring.datasource.username=postgres
spring.datasource.password=${anh12345}
spring.jpa.hibernate.ddl-auto=validate